Repository bcnmy/scw-contracts, pull requests merged in 2023-08, with the labels that each got.

#106 fix: YULException for Stack too Deep Error while compiling with viaIR: true
  contracts/smart-account/base/ModuleManager.sol
Labels: bug

#107 Fixes upon testing with bundler
  contracts/smart-account/modules/SmartContractOwnershipRegistryModule.sol
  contracts/smart-account/test/upgrades/v3/IHooks.sol
  contracts/smart-account/test/upgrades/v3/MockHookModule.sol
  contracts/smart-account/test/upgrades/v3/SmartAccountV3.sol
  contracts/smart-account/test/upgrades/v3/SpenderModule.sol
  contracts/smart-account/test/upgrades/v3/SpendingLimitsPoCModule.sol
  test/bundler-integration/module/SmartContractOwnershipRegistry.Module.specs.ts
  test/bundler-integration/smart-account/SA.Basics.specs.ts
  test/bundler-integration/smart-account/SA.Modules.specs.ts
  test/bundler-integration/upgrades/v2-to-v3/v2-to-v3-upgrade.specs.ts
  test/module/ECDSARegistry.Module.specs.ts
  test/module/SessionKeyManager.Module.specs.ts
  test/module/SessionValidationModules/ERC20SessionValidation.Module.specs.ts
  test/smart-account/SA.Basics.specs.ts
  test/smart-account/SA.Modules.specs.ts
  test/smart-account/SA.Setup.specs.ts
  test/smart-account/SA.UserOps.specs.ts
  test/upgrades/v2-to-v3/v2-to-v3-upgrade.specs.ts
Labels: tests

#114 feat: Deployment Scripts for Modular Smart Account Architecture
  .env.example
  .eslintrc.js
  .gitignore
  contracts/smart-account/SmartAccount.sol
  contracts/smart-account/paymasters/PaymasterHelpers.sol
  contracts/smart-account/paymasters/verifying/singleton/VerifyingSingletonPaymaster.sol
  hardhat.config.ts
  scripts/deploy.ts
  scripts/smart-account-factory-addstake.ts
  scripts/utils/index.ts
  test/Deployment.test.ts
  test/bundler-integration/smart-account/SA.Basics.specs.ts
  test/gas-benchmarks/Basic-Operations.specs.ts
  test/utils/userOp.ts
  yarn.lock
Labels: enhancement
